config/routes.rb
Fair::Application.routes.draw do

  resources :complaints

  resources :products

  get 'sign_up(/:invitation)' => 'login#sign_up'
  post 'sign_up' => 'login#create'
  get 'sign_in' => 'login#sign_in'
  post 'sign_in' => 'login#authenticate'
  match 'sign_out' => 'login#sign_out'
  post 'check' => 'login#check'

  get 'home' => 'subscribers#home'

  get 'invite' => 'subscribers#invite'
  post 'invite' => 'subscribers#deliver'
  get 'profile' => 'subscribers#edit'
  get 'password' => 'subscribers#password'
  get 'payment_password' => 'subscribers#payment_password'
  put 'profile' => 'subscribers#update'
  put 'password' => 'subscribers#update_password'
  put 'payment_password' => 'subscribers#update_payment_password'

  get 'regions/:id' => 'regions#index'

  get 'authorize/email' => 'subscribers#initiate_authorizing_email'
  get 'authorize' => 'subscribers#finish_authorizing_email'

  get 'reset_password' => 'login#initiate_reset_password'
  post 'reset_password' => 'login#deliver_reset_password'
  get 'reset_password/:code' => 'login#reset_password', :as => :reset_password_code
  put 'reset_password/:code' => 'login#finish_reset_password'

  resources :resources, :only => [ :create ]
  resources :shipping_addresses
  resources :returnings
  resources :bookmarks, :except => [ :new, :edit, :update ]
  resources :announcements, :only => [ :index, :show ]
  resources :notifications, :only => [ :index, :show ]
  resources :reviews
  resources :reports

  put 'notifications/:id/read' => 'notifications#read', :as => :read_notification
  delete 'notifications/:id' => 'notifications#stash'

  namespace :admin do
    resources :landing_pages
    resources :returnings, :only => [ :index, :show ]
    resources :complaints, :only => [ :index, :show ]
    resources :reports, :only => [ :index, :show ]
    resources :announcements
    resources :notifications

    get 'returnings/:id/accept' => 'returnings#accept', :as => :accept_returning
    put 'returnings/:id/accept' => 'returnings#do_accept'
    get 'returnings/:id/solve' => 'returnings#solve', :as => :solve_returning
    put 'returnings/:id/solve' => 'returnings#do_solve'
    get 'returnings/:id/reject' => 'returnings#reject', :as => :reject_returning
    put 'returnings/:id/reject' => 'returnings#do_reject'
    put 'complaints/:id/accept' => 'complaints#accept', :as => :accept_complaint
    get 'complaints/:id/edit' => 'complaints#edit', :as => :edit_complaint
    put 'complaints/:id/finish' => 'complaints#finish', :as => :finish_complaint
    put 'reports/:id/accept' => 'reports#accept', :as => :accept_report
    put 'reports/:id/finish' => 'reports#finish', :as => :finish_report

    get 'sign_in' => 'login#sign_in'
    post 'sign_in' => 'login#authenticate'
    match 'sign_out' => 'login#sign_out'
  end
  
  resources :orders
  
  resources :shopping do
    collection do
      get 'cart'
      get 'order'
      post 'save_order'
      get 'direct_order'
      get 'edit_address'
      put 'update_address'
      get 'new_address'
      post 'save_address'
    end
  end
  
  get "pays/new"
  get "pays/pay"
  get "pays/success"
  
  post "pays/alipay_notify"
  get  "pays/alipay_done"
  get  "pays/tenpay_done"

  root :to => 'products#index'
end

app/models/admin/landing_page.rb
class Admin::LandingPage < ActiveRecord::Base
  belongs_to :region
  attr_accessible :background_image, :domain
  validates :domain, :allow_nil => true, :format => {
    :with => /^(\*|([\w-]+\.){1,}[[:alpha:]]+)$/,
    :message => 'invalid'
  }
  validates :background_image, :presence => true

  def domain= s
    super
    self[:domain] = nil if self[:domain] && self[:domain].empty?
  end
end

app/controllers/admin/landing_pages_controller.rb
module Admin

  class LandingPagesController < AdminController

    include ApplicationHelper

    # GET /landing_pages
    # GET /landing_pages.json
    def index
      @landing_pages = LandingPage.all
      @prototype = LandingPage.new

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @landing_pages }
      end
    end

    # GET /landing_pages/1
    # GET /landing_pages/1.json
    def show
      @landing_page = LandingPage.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @landing_page }
      end
    end

    # GET /landing_pages/new
    # GET /landing_pages/new.json
    def new
      @landing_page = LandingPage.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @landing_page }
      end
    end

    # GET /landing_pages/1/edit
    def edit
      @landing_page = LandingPage.find(params[:id])
    end

    # POST /landing_pages
    # POST /landing_pages.json
    def create
      @landing_page = LandingPage.new params[:admin_landing_page]

      respond_to do |format|
        if File.exists?(resource_path @landing_page.background_image) &&
            @landing_page.save
          format.html { redirect_to @landing_page, notice: 'Landing page was successfully created.' }
          format.json { render json: @landing_page, status: :created, location: @landing_page }
        else
          format.html { render action: "new" }
          format.json { render json: @landing_page.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /landing_pages/1
    # PUT /landing_pages/1.json
    def update
      @landing_page = LandingPage.find(params[:id])

      respond_to do |format|
        if File.exists?(resource_path params[:admin_landing_page][:background_image]) &&
            @landing_page.update_attributes(params[:admin_landing_page])
          format.html { redirect_to @landing_page, notice: 'Landing page was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @landing_page.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /landing_pages/1
    # DELETE /landing_pages/1.json
    def destroy
      @landing_page = LandingPage.find(params[:id])
      @landing_page.destroy

      respond_to do |format|
        format.html { redirect_to admin_landing_pages_url }
        format.json { head :no_content }
      end
    end
  end

end

app/helpers/admin/landing_pages_helper.rb
module Admin::LandingPagesHelper
end

app/views/admin/landing_pages/_form.html.erb
<%= form_for(@landing_page) do |f| %>
<% if @landing_page.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@landing_page.errors.count, "error") %> prohibited this landing_page from being saved:</h2>

  <ul>
    <% @landing_page.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :domain %><br />
  <%= f.text_field :domain %>
</div>
<div class="field file">
  <%= label_tag :load %><br />
  <%= render :partial => "resources/file_combo", :object => (f.hidden_field :background_image) %>
</div>
<div class="actions">
  <%= f.submit :value => 'Upload' %>
</div>
<% end %>

<ul class="notes">
  <li>
    domain name should be 'baidu.com' like,
    or <code>BLANK</code> for no referer, '*' for else.
  </li>
</ul>

app/views/admin/landing_pages/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @landing_page %> |
<%= link_to 'Back', admin_landing_pages_path %>

app/views/admin/landing_pages/index.html.erb
<ul>
  <% @landing_pages.each do |landing_page| %>
  <li class="page">
    <%= image_tag resource_url(landing_page.background_image), class: "thumbnail" %>
    <div class="actions">
      <h5><%= landing_page.domain || 'N/A' %></h5>
      <ul>
	<li><%= link_to 'Show', landing_page %></li>
	<li><%= link_to 'Edit', edit_admin_landing_page_path(landing_page) %></li>
	<li><%= link_to 'Destroy', landing_page, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </li>
  <% end %>
</ul>
<div class="clear"></div>

<%= link_to 'New Landing page', new_admin_landing_page_path %>

app/views/admin/landing_pages/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_landing_pages_path %>

app/views/admin/landing_pages/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<ul>
  <li class="page">
    <%= image_tag resource_url(@landing_page.background_image), class: "thumbnail" %>
    <div class="actions">
      <h5><%= @landing_page.domain %></h5>
      <ul>
	<li><%= link_to 'Edit', edit_admin_landing_page_path(@landing_page) %></li>
	<li><%= link_to 'Back', admin_landing_pages_path %></li>
      </ul>
    </div>
  </li>
</dl>