config/routes.rb
Fair::Application.routes.draw do

  resources :complaints

  resources :products

  get 'sign_up(/:invitation)' => 'login#sign_up'
  post 'sign_up' => 'login#create'
  get 'sign_in' => 'login#sign_in'
  post 'sign_in' => 'login#authenticate'
  match 'sign_out' => 'login#sign_out'
  post 'check' => 'login#check'

  get 'home' => 'subscribers#home'

  get 'invite' => 'subscribers#invite'
  post 'invite' => 'subscribers#deliver'
  get 'profile' => 'subscribers#edit'
  get 'password' => 'subscribers#password'
  get 'payment_password' => 'subscribers#payment_password'
  put 'profile' => 'subscribers#update'
  put 'password' => 'subscribers#update_password'
  put 'payment_password' => 'subscribers#update_payment_password'

  get 'regions/:id' => 'regions#index'

  get 'authorize/email' => 'subscribers#initiate_authorizing_email'
  get 'authorize' => 'subscribers#finish_authorizing_email'

  get 'reset_password' => 'login#initiate_reset_password'
  post 'reset_password' => 'login#deliver_reset_password'
  get 'reset_password/:code' => 'login#reset_password', :as => :reset_password_code
  put 'reset_password/:code' => 'login#finish_reset_password'

  resources :resources, :only => [ :create ]
  resources :shipping_addresses
  resources :returnings
  resources :bookmarks, :except => [ :new, :edit, :update ]
  resources :announcements, :only => [ :index, :show ]
  resources :notifications, :only => [ :index, :show ]
  resources :reviews
  resources :reports

  put 'notifications/:id/read' => 'notifications#read', :as => :read_notification
  delete 'notifications/:id' => 'notifications#stash'

  namespace :admin do
    resources :landing_pages
    resources :returnings, :only => [ :index, :show ]
    resources :complaints, :only => [ :index, :show ]
    resources :reports, :only => [ :index, :show ]
    resources :announcements
    resources :notifications

    get 'returnings/:id/accept' => 'returnings#accept', :as => :accept_returning
    put 'returnings/:id/accept' => 'returnings#do_accept'
    get 'returnings/:id/solve' => 'returnings#solve', :as => :solve_returning
    put 'returnings/:id/solve' => 'returnings#do_solve'
    get 'returnings/:id/reject' => 'returnings#reject', :as => :reject_returning
    put 'returnings/:id/reject' => 'returnings#do_reject'
    put 'complaints/:id/accept' => 'complaints#accept', :as => :accept_complaint
    get 'complaints/:id/edit' => 'complaints#edit', :as => :edit_complaint
    put 'complaints/:id/finish' => 'complaints#finish', :as => :finish_complaint
    put 'reports/:id/accept' => 'reports#accept', :as => :accept_report
    put 'reports/:id/finish' => 'reports#finish', :as => :finish_report

    get 'sign_in' => 'login#sign_in'
    post 'sign_in' => 'login#authenticate'
    match 'sign_out' => 'login#sign_out'
  end
  
  resources :orders
  
  resources :shopping do
    collection do
      get 'cart'
      get 'order'
      post 'save_order'
      get 'direct_order'
      get 'edit_address'
      put 'update_address'
      get 'new_address'
      post 'save_address'
    end
  end
  
  get "pays/new"
  get "pays/pay"
  get "pays/success"
  
  post "pays/alipay_notify"
  get  "pays/alipay_done"
  get  "pays/tenpay_done"

  root :to => 'products#index'
end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :subscriber
  belongs_to :product
  attr_accessible :receipt_date, :receipt_photo, :receipt_price, :retailer
  validates :subscriber, :presence => true
  validates :product, :presence => true
  validates :price, :presence => true
  validates :receipt_price, :presence => true
  validates :receipt_photo, :presence => true
  validate :receipt_price_should_be_less_than_price

  def accept
    self.accepted_at = Time.now if self.accepted_at.nil? && self.finished_at.nil?
  end

  def finish
    self.finished_at = Time.now if self.finished_at.nil?
  end

  # ------------------------------------------------------------
  private

  def receipt_price_should_be_less_than_price
    errors.add(:receipt_price, "should be less than price") if price && receipt_price && price <= receipt_price
  end

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController

  def index
    @reports = Report.page(params[:page]).order('created_at DESC')
  end

  def show
    @report = Report.find(params[:id])
  end

  def accept
    @report = Report.find(params[:id])
    @report.accept
    @report.save
    redirect_to admin_report_url(@report)
  end

  def finish
    @report = Report.find(params[:id])
    @report.finish
    @report.save
    redirect_to admin_report_url(@report)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout "subscribers"

  include ApplicationHelper

  # GET /reports
  # GET /reports.json
  def index
    @reports = @subscriber.reports.page(params[:page]).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = @subscriber.reports.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = @subscriber.reports.new
    @report.product = Product.find_by_id(params[:product])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = @subscriber.reports.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = @subscriber.reports.new(params[:report])
    @report.product = Product.find_by_id(params[:product])
    @report.price = @report.product && @report.product.price
    @report.receipt_photo = nil unless @report.receipt_photo && File.exists?(resource_path @report.receipt_photo)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = @subscriber.reports.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admin/reports/index.html.erb
<% if @reports.empty? %>
<p>No report.</p>
<% else %>
<ul>
  <% @reports.each do |report| %>
  <li class="product">
    <%= render :partial => "bookmarks/product", :object => report.product %>
    <div class="report">
      <span class="subscriber"><%= report.subscriber.email %></span>
      <span class="retailer"><%= report.retailer %></span>
      <span class="receipt_date"><%= report.receipt_date %></span>
      <span class="receipt_price">￥<%= report.receipt_price %></span>
      <span class="price">￥<%= report.price %></span>
      <h5><%= report.finished_at && format("%s [SOLVED]", report.finished_at) ||
	      report.accepted_at && format("%s [ACCEPTED]", report.accepted_at) %></h5>
    </div>
    <div class="actions">
      <%= link_to 'Show', admin_report_path(report) %>
      <% unless report.finished_at %>
      <% unless report.accepted_at %>
      <%= link_to 'Accept', admin_accept_report_path(report), method: :put, data: { confirm: 'Are you sure?' } %>
      <% else %>
      <%= link_to 'Finish', admin_finish_report_path(report), method: :put, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>
<% end %>

<%= will_paginate %>

app/views/admin/reports/show.html.erb
<div class="product">
  <%= render :partial => "bookmarks/product", :object => @report.product %>
  <div class="report">
    <span class="subscriber"><%= @report.subscriber.email %></span>
    <span class="retailer"><%= @report.retailer %></span>
    <span class="receipt_date"><%= @report.receipt_date %></span>
    <span class="receipt_price">￥<%= @report.receipt_price %></span>
    <span class="price">￥<%= @report.price %></span>
    <h5><%= @report.finished_at && format("%s [SOLVED]", @report.finished_at) ||
	    @report.accepted_at && format("%s [ACCEPTED]", @report.accepted_at) %></h5>
  </div>
  <div class="actions">
    <%= link_to 'Show', admin_report_path(@report) %>
    <% unless @report.finished_at %>
    <% unless @report.accepted_at %>
    <%= link_to 'Accept', admin_accept_report_path(@report), method: :put, data: { confirm: 'Are you sure?' } %>
    <% else %>
    <%= link_to 'Finish', admin_finish_report_path(@report), method: :put, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% end %>
  </div>
  <img class="receipt" src="<%= resource_url @report.receipt_photo %>" />
</div>

<%= link_to 'Back', admin_reports_path %>