config/routes.rb
Fair::Application.routes.draw do

  resources :complaints

  resources :products

  get 'sign_up(/:invitation)' => 'login#sign_up'
  post 'sign_up' => 'login#create'
  get 'sign_in' => 'login#sign_in'
  post 'sign_in' => 'login#authenticate'
  match 'sign_out' => 'login#sign_out'
  post 'check' => 'login#check'

  get 'home' => 'subscribers#home'

  get 'invite' => 'subscribers#invite'
  post 'invite' => 'subscribers#deliver'
  get 'profile' => 'subscribers#edit'
  get 'password' => 'subscribers#password'
  get 'payment_password' => 'subscribers#payment_password'
  put 'profile' => 'subscribers#update'
  put 'password' => 'subscribers#update_password'
  put 'payment_password' => 'subscribers#update_payment_password'

  get 'regions/:id' => 'regions#index'

  get 'authorize/email' => 'subscribers#initiate_authorizing_email'
  get 'authorize' => 'subscribers#finish_authorizing_email'

  get 'reset_password' => 'login#initiate_reset_password'
  post 'reset_password' => 'login#deliver_reset_password'
  get 'reset_password/:code' => 'login#reset_password', :as => :reset_password_code
  put 'reset_password/:code' => 'login#finish_reset_password'

  resources :resources, :only => [ :create ]
  resources :shipping_addresses
  resources :returnings
  resources :bookmarks, :except => [ :new, :edit, :update ]
  resources :announcements, :only => [ :index, :show ]
  resources :notifications, :only => [ :index, :show ]
  resources :reviews
  resources :reports

  put 'notifications/:id/read' => 'notifications#read', :as => :read_notification
  delete 'notifications/:id' => 'notifications#stash'

  namespace :admin do
    resources :landing_pages
    resources :returnings, :only => [ :index, :show ]
    resources :complaints, :only => [ :index, :show ]
    resources :reports, :only => [ :index, :show ]
    resources :announcements
    resources :notifications

    get 'returnings/:id/accept' => 'returnings#accept', :as => :accept_returning
    put 'returnings/:id/accept' => 'returnings#do_accept'
    get 'returnings/:id/solve' => 'returnings#solve', :as => :solve_returning
    put 'returnings/:id/solve' => 'returnings#do_solve'
    get 'returnings/:id/reject' => 'returnings#reject', :as => :reject_returning
    put 'returnings/:id/reject' => 'returnings#do_reject'
    put 'complaints/:id/accept' => 'complaints#accept', :as => :accept_complaint
    get 'complaints/:id/edit' => 'complaints#edit', :as => :edit_complaint
    put 'complaints/:id/finish' => 'complaints#finish', :as => :finish_complaint
    put 'reports/:id/accept' => 'reports#accept', :as => :accept_report
    put 'reports/:id/finish' => 'reports#finish', :as => :finish_report

    get 'sign_in' => 'login#sign_in'
    post 'sign_in' => 'login#authenticate'
    match 'sign_out' => 'login#sign_out'
  end
  
  resources :orders
  
  resources :shopping do
    collection do
      get 'cart'
      get 'order'
      post 'save_order'
      get 'direct_order'
      get 'edit_address'
      put 'update_address'
      get 'new_address'
      post 'save_address'
    end
  end
  
  get "pays/new"
  get "pays/pay"
  get "pays/success"
  
  post "pays/alipay_notify"
  get  "pays/alipay_done"
  get  "pays/tenpay_done"

  root :to => 'products#index'
end

app/models/subscriber.rb
require 'salt'

class Subscriber < ActiveRecord::Base
  attr_accessible :email, :nickname, :mobile
  belongs_to :initiator, :class_name => "Subscriber"
  belongs_to :region
  has_many :invitees, :class_name => "Subscriber", :foreign_key => "initiator_id"
  has_one :detail, :class_name => "SubscriberDetail"
  has_one :authorization
  has_many :invitations
  has_many :shipping_addresses
  has_many :orders
  has_many :credit_components, :class_name => "Credit"
  has_many :returnings
  has_many :bookmarks
  has_many :reviews
  has_many :complaints
  has_many :reports
  has_many :notifications, :foreign_key => "to_id"

  validates :email, :uniqueness => true, :presence => true, :format => {
    :with => /^[[:alnum:]._%-]+@[[:alnum:].-]+\.[[:alpha:]]{2,4}$/,
    :message => "invalid"
  }
  validates :mobile, :allow_nil => true, :uniqueness => true

  include Salt

  def consume_credit(amount)
    self.credit_components.where("expired_at >= ?", Date.today).order("expired_at").each do
      | c |

      c.subscriber = self       # no IdentityMap
      amount = c.consume(amount)
      break if amount < 0.01
    end
    amount
  end

  def payback_credit(amount)
    # TODO: payback MUST consult corresponding consume,
    # via order or so.
  end

end

app/controllers/subscribers_controller.rb
require 'b64_uuid'

class SubscribersController < ApplicationController

  skip_before_filter :authorize, :only => [ :finish_authorizing_email ]

  def home
    @subscriber = Subscriber.find(session[:subscriber_id])
  end

  def invite
    @code = get_invitation_code
    render :layout => 'application'
  end

  def deliver
    code = get_invitation_code
    params[:email].each do
      | each |

      if each =~ /\b[[:alnum:]._%-]+@[[:alnum:].-]+\.[[:alpha:]]{2,4}\b/ &&
          Subscriber.find_by_email(each).nil?
        AccountNotifier.invite(each, (sign_up_url :invitation => code)).deliver
      end
    end
    redirect_to :action => 'invite'
  end

  def initiate_authorizing_email
    code = get_authorization_code
    AccountNotifier.authorize(@subscriber.email, (authorize_url :q => code)).deliver
  end

  def finish_authorizing_email
    auth = Authorization.find_by_code(params[:q])
    unless auth.nil? || auth.expired? || auth.email != auth.subscriber.email
      auth.subscriber.detail ||= SubscriberDetail.new
      auth.subscriber.detail.email_authorized_at = Time.now
      auth.subscriber.detail.save
      @subscriber = auth.subscriber
    end
    render :layout => 'application'
  end

  def edit
    @subscriber = Subscriber.find(session[:subscriber_id])
  end

  def password
    @subscriber = Subscriber.find(session[:subscriber_id])
  end

  def payment_password
    @subscriber = Subscriber.find(session[:subscriber_id])
  end

  def update
    @subscriber = Subscriber.find(session[:subscriber_id])
    if @subscriber.update_attributes params[:subscriber]
      redirect_to :action => 'edit'
    else
      render :action => 'edit'
    end
  end

  def update_password
    @subscriber = Subscriber.find(session[:subscriber_id])
    if @subscriber.authenticate(params[:old]) &&
        params[:confirm] == params[:new]
      @subscriber.password = params[:new]
      if @subscriber.save
        redirect_to :action => 'password'
        return
      end
    end
    render :action => 'password'
  end

  def update_payment_password
    @subscriber = Subscriber.find(session[:subscriber_id])
    @subscriber.detail ||= SubscriberDetail.new
    if (@subscriber.detail.payment_password.nil? ||
        @subscriber.detail.payment_authenticate(params[:old])) &&
        params[:confirm] == params[:new]
      @subscriber.detail.payment_password = params[:new]
      if @subscriber.detail.save
        redirect_to :action => 'payment_password'
        return
      end
    end
    render :action => 'payment_password'
  end

  # ------------------------------------------------------------
  private

  def get_invitation_code
    @subscriber = Subscriber.find(session[:subscriber_id])
    if @subscriber.invitations.empty?
      invt = @subscriber.invitations.new
      invt.code = B64UUID.generate
      invt.save
    end
    @subscriber.invitations.last.code
  end

  def get_authorization_code
    @subscriber = Subscriber.find(session[:subscriber_id])
    @subscriber.authorization ||= Authorization.new
    @subscriber.authorization.code = B64UUID.generate
    @subscriber.authorization.email = @subscriber.email
    @subscriber.authorization.expire_at = Time.now + 3600 # TODO: authorization_ttl
    @subscriber.authorization.save
  end

end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/edit.html.erb
<%= form_for(@subscriber, :url => profile_path) do |f| %>
<% if @subscriber.errors.any? %>
<div class="error_explanation">
  <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>
  <ul>
    <% @subscriber.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <h2>
    <%= @subscriber.email %>
    <% unless @subscriber.detail && @subscriber.detail.email_authorized_at %>
    <a href="<%= authorize_email_path %>">Authorize</a>
    <% end %>
  </h2>
</div>
<div class="field">
  <%= f.label :nickname %><br />
  <%= f.text_field :nickname %>
</div>
<div class="field">
  <%= f.label :mobile %><br />
  <%= f.text_field :mobile %>
</div>
<div class="action">
  <%= f.submit :value => 'Save' %>
</div>
<% end %>

app/views/subscribers/finish_authorizing_email.html.erb
<% if @subscriber && @subscriber.detail && @subscriber.detail.email_authorized_at %>
<p><a href="<%= home_path %>"><%= @subscriber.email %></a> authorized.</p>
<% else %>
<p>Invalid authorization or expired.</p>
<% end %>

app/views/subscribers/home.html.erb
<h1>Home</h1>

<p>This is <%= @subscriber.email %> (<%= @subscriber.id %>).</p>

app/views/subscribers/initiate_authorizing_email.html.erb
<p>Authorization mail delivered to <b><%= @subscriber.email %></b>.</p>

app/views/subscribers/invite.html.erb
<div class="major">
  <div class="left">
    <%= form_tag do %>
    <div class="prologue"></div>
    <div class="email">
      <input type="text" name="email[]" /><br />
      <%= submit_tag "" %>
    </div>
    <% end %>
    <div class="link">
      <input type="text" readonly="true" value="<%= sign_up_url :invitation => @code %>" />
    </div>
    <a href="javascript:;" class="invt_check"></a>
  </div>
  <div class="right">
    <ul>
      <li class="bonus_1"></li>
      <li class="bonus_2"></li>
      <li class="bonus_3"></li>
      <li class="bonus_4"></li>
    </ul>
  </div>
  <div class="clear">
  </div>
</div>

app/views/subscribers/password.html.erb
<%= form_tag password_path, :method => :put do %>
<div class="field">
  <%= label_tag :old %>
  <%= password_field_tag :old %>
</div>
<div class="field">
  <%= label_tag :new %>
  <%= password_field_tag :new %>
</div>
<div class="field">
  <%= label_tag :confirm %>
  <%= password_field_tag :confirm %>
</div>
<div class="actions">
  <%= submit_tag "Save" %>
</div>
<% end %>

app/views/subscribers/payment_password.html.erb
<%= form_tag payment_password_path, :method => :put do %>
<% unless @subscriber.detail.nil? || @subscriber.detail.payment_password.nil? %>
<div class="field">
  <%= label_tag :old %>
  <%= password_field_tag :old %>
</div>
<% end %>
<div class="field">
  <%= label_tag :new %>
  <%= password_field_tag :new %>
</div>
<div class="field">
  <%= label_tag :confirm %>
  <%= password_field_tag :confirm %>
</div>
<div class="actions">
  <%= submit_tag "Save" %>
</div>
<% end %>